version: "2"
 
services:
 codesys:
   image: hilschernetpi/netpi-codesys-basis:latest
   network_mode: "host"
   restart: always
   ports:
     - 22:22
   devices:
     - "/dev/vcio:/dev/vcio"
     - "/dev/hidraw0:/dev/hidraw0"
     - "/dev/spidev0.0:/dev/spidev0.0"
     - "/dev/net/tun:/dev/net/tun"
     - "/dev/sda1:/dev/sda1"
   privileged: true
   environment:
     - SSHPORT=22
 
 nodered:
   restart: unless-stopped
   image: hilschernetpi/netpi-nodered:latest
   ports:
     - "1880:1880"
   networks:
     - host
   restart: always
   user: root
   privileged: true
 
 influxdb:
   restart: unless-stopped
   image: influxdb:latest
   restart: always
   ports:
     - "8086:8086"
   volumes:
     - influxdb-storage:/var/lib/influxdb
   networks:
     - bridgeNetwork
   environment:
     - INFLUXDB_DB=db0
     - INFLUXDB_ADMIN_ENABLED=true
     - INFLUXDB_ADMIN_USER=admin
     - INFLUXDB_ADMIN_PASSWORD=${ADMIN_PWD}
     - INFLUXDB_USER=user
     - INFLUXDB_USER_PASSWORD=${USER_PWD}

networks:
   bridgeNetwork:
       driver: bridge
       ipam:
           driver: default
           config:
               - subnet: 172.30.0.0/24
                 gateway: 172.30.0.1
                 
volumes:
    influxdb-storage:
