version: "2"
 
services:
 codesys:
   image: hilschernetpi/netpi-codesys-basis:latest
   network_mode: "host"
   restart: always
   devices:
     - "/dev/vcio:/dev/vcio"
     - "/dev/hidraw0:/dev/hidraw0"
     - "/dev/spidev0.0:/dev/spidev0.0"
     - "/dev/net/tun:/dev/net/tun"
     - "/dev/sda1:/dev/sda1"
   privileged: true
 
 nodered:
   image: hilschernetpi/netpi-nodered:latest
   ports:
     - "1880:1880"
   networks:
     - bridgeNetwork
   restart: always
   user: root
   privileged: true
 
 influxdb:
   image: influxdb:latest
   restart: always
   ports:
     - "8086:8086"
   volumes:
     - influxdb-storage:/var/lib/influxdb
   networks:
     - bridgeNetwork
   environment:
     - INFLUXDB_DB=db0
     - INFLUXDB_ADMIN_ENABLED=true
     - INFLUXDB_ADMIN_USER=admin
     - INFLUXDB_ADMIN_PASSWORD="gruppe=422"
     - INFLUXDB_USER=user
     - INFLUXDB_USER_PASSWORD="gruppe=422"
 
 grafana:
   image: grafana/grafana:latest
   restart: always
   ports:
     - "3000:3000"
   networks:
     - bridgeNetwork
   volumes:
     - grafana-storage:/var/lib/grafana
     - ./grafana-provisioning/:/etc/grafana/provisioning
   depends_on:
     - influxdb

 chronograf:
   image: chronograf:latest
   ports:
     - '127.0.0.1:8888:8888'
   volumes:
     - chronograf-storage:/var/lib/chronograf
   depends_on:
     - influxdb
   environment:
     - INFLUXDB_URL=http://influxdb:8086
     - INFLUXDB_USERNAME=admin
     - INFLUXDB_PASSWORD="gruppe=422"

networks:
   bridgeNetwork:
       driver: bridge
       ipam:
           driver: default
           config:
               - subnet: 172.30.0.0/24
                 gateway: 172.30.0.1
volumes:
    influxdb-storage:
    chronograf-storage:
    grafana-storage: